// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAincLdHjoy0yEw8Z8_uzMcQzW2DoR90dk',
    appId: '1:932204367190:web:385438c497306ce82b1af7',
    messagingSenderId: '932204367190',
    projectId: 'wasselni-application',
    authDomain: 'wasselni-application.firebaseapp.com',
    storageBucket: 'wasselni-application.firebasestorage.app',
    measurementId: 'G-EZ6RVF3575',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJxJLv9mRISMVfnfj-THVIGPwKcigJbUE',
    appId: '1:932204367190:android:706d8a14b07f16402b1af7',
    messagingSenderId: '932204367190',
    projectId: 'wasselni-application',
    storageBucket: 'wasselni-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7_imIM6WqzRqna_KPOLEVriRXWmxOdjc',
    appId: '1:932204367190:ios:f9ba050ca2bd7e5b2b1af7',
    messagingSenderId: '932204367190',
    projectId: 'wasselni-application',
    storageBucket: 'wasselni-application.firebasestorage.app',
    iosClientId: '932204367190-6ocaq0fqsdm0ffonl7t1qgrnr0snu9p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7_imIM6WqzRqna_KPOLEVriRXWmxOdjc',
    appId: '1:932204367190:ios:f9ba050ca2bd7e5b2b1af7',
    messagingSenderId: '932204367190',
    projectId: 'wasselni-application',
    storageBucket: 'wasselni-application.firebasestorage.app',
    iosClientId: '932204367190-6ocaq0fqsdm0ffonl7t1qgrnr0snu9p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAincLdHjoy0yEw8Z8_uzMcQzW2DoR90dk',
    appId: '1:932204367190:web:5c21194086a63c8c2b1af7',
    messagingSenderId: '932204367190',
    projectId: 'wasselni-application',
    authDomain: 'wasselni-application.firebaseapp.com',
    storageBucket: 'wasselni-application.firebasestorage.app',
    measurementId: 'G-5T9YP4QJVR',
  );

}